namespace AlgorithmCoding
{
    public static class FindTheDifference
    {
        // You are given two strings s and t.
        // String t is generated by random shuffling string s and then add one more letter at a random position.
        // Return the letter that was added to t.

        // Input: s = "abcd", t = "abcde"
        // Output: "e"
        // Explanation: 'e' is the letter that was added.
        public static char FindTheDifferenceResult(string s, string t)
        {
            var total = 0;

            for (int i = 0; i < s.Length; i++)
            {
                total-=s[i];
                total+=t[i];
            }

            return (char)(total + t[t.Length - 1]);
        }
    }
}
